### ISSUE TITLE
 set 'duplicate-packets 0' in server command always upload failed

### ISSUE THREAD

**Issue by jinxsong123** [altugbakan/rs-tftpd#10]
when I start the server using this command 'tftpd  -p 8888 -d  /tmp/tftp --overwrite  --duplicate-packets 0'

but client upload the file  always  'Transfer timed out.'

![图片](https://github.com/altugbakan/rs-tftpd/assets/52711267/63c40fe3-8be8-437d-9eef-12c2d3c0d354)

the Version:  tftpd v0.2.8

**Comment by altugbakan** [comment]
Thanks for catching this, I will try to implement a testing suite for the server so that these bugs can be easily caught in the future.

**Comment by altugbakan** [comment]
Fixed by #11
