### ISSUE TITLE
Add support that download and upload to different directory

### ISSUE THREAD

**Issue by shuyuImpossible** [altugbakan/rs-tftpd#13]
Can we add parameters in config (directoryupload, directorydownload)?
If both directoryupload and directorydownload are set, then tftp download from directorydownload and tftp upload to directoryupload.

**Comment by altugbakan** [comment]
This sounds like a really cool idea! We can add `--upload-directory` and `--download-directory` flags to add the functionality.

Would you like to work on it? If not, I can work on this in the following days.

**Comment by shuyuImpossible** [comment]
I can try to work on it.

**Comment by altugbakan** [comment]
Fixed with #14
