### ISSUE TITLE
rs-tftpc

### ISSUE THREAD

**Issue by tardyp** [altugbakan/rs-tftpd#21]
Hello,

Your crate already implements most of what is needed to implement a tftp client.
Just need to add a few serializer, deserializer for the existing messages, and then a client module.

Would you accept some MR to go that way?

**Comment by altugbakan** [comment]
Hello!

I think that would be a great idea, I also had that in my mind, but never got to work on it since I couldn’t find the time.

It would definitely be a great addition, and if you need help please let me know.

**Comment by altugbakan** [comment]
Implemented with #22
