### ISSUE TITLE
Support absolute filepath.

### ISSUE THREAD

**Issue by mayurikini** [altugbakan/rs-tftpd#29]
Continuing on https://github.com/altugbakan/rs-tftpd/issues/24#issuecomment-2266241827

During boot process the requests for config files are absolute paths, which leads to \test.cfg or /test.cfg request (for windows and linux). 

Could we add a patch to support this by ignoring first character if it is "\\" or "/"?

Here is a sample code that can be added in both server.rs and client_config.rs:
```
                    let filename = file_name.trim_start_matches(|c| c == '/' || c == '\\').to_string();
```

**Comment by stappersg** [comment]
This issue can (and should) be closed.

**Comment by altugbakan** [comment]
Fixed with #30

**Comment by calandoa** [comment]
This means that `tftpc -u /folder/upload.bin` will not work (client will looks for `folder/upload.bin`) but on Windows, `tftpc.exe-u C:/folder/upload.bin` will works !

Is it really what we want ?

I understand absolute paths must not be accepted on the server side, and discarding the starting slash can be an handy workaround, but for client mode in upload, this is a problem.

**Comment by calandoa** [comment]
Ok I will include in next patch an additional parameter to
`convert_file_path(filename: &str)`
like
`convert_file_path(filename: &str, fix_abs : bool)`
so server or client can choose their desired behavior
