### ISSUE TITLE
Track file transfer status

### ISSUE THREAD

**Issue by mayurikini** [altugbakan/rs-tftpd#33]
Hi! I was wondering if we can have an option to track if a given file was served or not (served/ not served (file not found)). 
I know we are logging them. But for my case parsing through the logs to maintain/store the history data isn’t feasible.

Let me know your thoughts on this.

**Comment by stappersg** [comment]
On Wed, Nov 20, 2024 at 09:08:13PM -0800, Mayuri Kini wrote:
> 
> Let me know your thoughts on this.
> 

Patches welcome

**Comment by mayurikini** [comment]
@altugbakan requesting you to please take a look at my design before I make code changes and get PR out.

Adding an option -ft that takes in directory. 
This directory is where we will create a folder with requesting client ip addr and store the file status in filename.log.

When request comes in content will be "PENDING" / "PROCESSING". File is sent "SUCCESS". In case of error, content will be "ERROR :<kind of error>". Content will overwrite in the log file to maintain last status.

-ft "destination-folder/"

here is what console log looks like and what the file and file content will be
```
Sending file abc to 127.0.0.0
destination-folder/127.0.0.0/abc.log --> Content "PENDING"
Sent file abc to 127.0.0.0
destination-folder/127.0.0.0/abc.log --> Content "SUCCESS"
Sending file pqr to 127.0.0.0
destination-folder/127.0.0.0/pqr.log --> Content "PENDING"
File pqr not found to 127.0.0.0
destination-folder/127.0.0.0/pqr.log --> Content "ERROR: FileNotFound"
```

Let me know if this looks good.

**Comment by altugbakan** [comment]
Hello, and thank you for asking about your design first.

What I am not sure about is needing a second log directory, since we can just redirect the output to anywhere we like. Replacing the status of the streaming file seems hard to accomplish, since there can be multiple transfers and modifying just a text file seems too much work for you also.

So you can redirect the output to a file using something like `tftpd [PARAMS] > log.txt`. What is your actual use case for this? I get that your use case might be hard to accomplish with this, but I couldn’t see the added value for this change, since the maintenance cost will be too high.

**Comment by mayurikini** [comment]
Thanks for your feedback. I would like to clarify that the purpose of the design is not just about logging but to communicate file transfer statuses to a different process over IPC channel. Redirecting doesn'tr solve the issue, as in additiong to this tracker file I want the console output as well. I am okay if we create 1 file per client. 

```
Sending file abc to 127.0.0.0
destination-folder/127.0.0.0.log --> Content "abc PENDING"
Sent file abc to 127.0.0.0
destination-folder/127.0.0.0.log --> Content "abc SUCCESS"
Sending file pqr to 127.0.0.0
destination-folder/127.0.0.0.log --> Content "pqr PENDING"
File pqr not found to 127.0.0.0
destination-folder/127.0.0.0.log --> Content "pqr ERROR: FileNotFound"

```
This will help me with
1. external process to monitor the status without direct communication with the tftp program. 
2. status of files wrt to client is isolated so no need to parse centralized log file.
3.just having filename and status will help in keeping the data storage to a minimum.

**Comment by altugbakan** [comment]
I get how it helps your case, but can’t see how it will help tftpd as a feature. For me this calls for an additional translation layer between two programs. I’m closing this as not planned for now.
