### ISSUE TITLE
New version rs-tftpd download become very slow

### ISSUE THREAD

**Issue by jinxsong123** [altugbakan/rs-tftpd#9]
hi,  Have you noticed that the download speed of the new version of tftp has become very slow?
I tested it,  download 10M file, speet 30s
<img width="413" alt="MicrosoftTeams-image (6)" src="https://github.com/altugbakan/rs-tftpd/assets/52711267/bf772127-4d20-40c1-a7c2-5134fac0396e">

The version is  **v0.2.8**
   Updating crates.io index
  Downloaded tftpd v0.2.8
  Downloaded 1 crate (15.2 KB) in 3.34s
  Installing tftpd v0.2.8
    Updating crates.io index
   Compiling tftpd v0.2.8
    Finished release [optimized] target(s) in 8.76s
   Replacing /home/jinxsong/.cargo/bin/tftpd
    Replaced package `tftpd v0.2.6` with `tftpd v0.2.8` (executable `tftpd`)

**Comment by jinxsong123** [comment]
I start the server using  " tftpd  -p 8888 -d  /tmp/tftp --duplicate-packets 0" seems ok, so the default value of --duplicate-packets seems not 0

**Comment by altugbakan** [comment]
Ahh, thanks for catching that! Would you like to make a PR with the fix? If not, I can check that out later.

**Comment by jinxsong123** [comment]
Sorry, I am not familiar with Rust

**Comment by altugbakan** [comment]
No worries! I was just asking it to welcome contributions.

**Comment by altugbakan** [comment]
Fixed with #11
